name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_challenge2.py
      id: test_challenge2-py
      uses: classroom-resources/autograding-python-grader@v1
      env:
        C2_MCQF_1: ${{ vars.C2_MCQF_1 }}
        C2_MCQF_2: ${{ vars.C2_MCQF_2 }}
        C2_MCQF_3: ${{ vars.C2_MCQF_3 }}
        C2_MCQF_4: ${{ vars.C2_MCQF_4 }}
        C2_MCQF_5: ${{ vars.C2_MCQF_5 }}
        C2_TOTAL_NA: ${{ vars.C2_TOTAL_NA }}
        C2_FORBIDDEN_COLS: ${{ vars.C2_FORBIDDEN_COLS }}
      with:
        timeout: 10
        max-score: 9
        setup-command: |
          pip install -r requirements.txt
          jupyter nbconvert --to python challenge-2.ipynb --output challenge_2_export.py
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_CHALLENGE2-PY_RESULTS: "${{steps.test_challenge2-py.outputs.result}}"
      with:
        runners: test_challenge2-py